# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Inconsistencies with data
    url: /#datainconsistencies
    weight: 11
  - name: Videos
    # TODO migrate to youtube.data-inconsistencies.datajourney.expert once set up properly
    # url: https://www.youtube.com/@datainconsistencies/
    url: http://youtube.data-inconsistencies.datajourney.expert
    #url: https://youtube.data-inconsistencies.datajourney.expert
    #url: /#features
    weight: 30
  
  #- name: Features
  #  url: /#features
  #  weight: 20
  #- name: Solutions
  #  url: /#solutions
  #  weight: 30
  #- name: Resources
  #  weight: 40
  #  hasChildren: true
  - name: Blog
    url: blog/
    weight: 40
  #- parent: Resources
  #  name: Blog
  #  url: blog/
