# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: green

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: 'Data Experts'
    org_name: 'datainconsistencies'
    description: 'Data inconsistencies, architecuture and real world stories'
    twitter: ''
  analytics:
    google_analytics: 'G-GV8QDDVB6Q'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
    google_tag_manager: 'G-GV8QDDVB6Q'
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "data-inconsistencies-logo.jpg"
    # button:
    #   enable: true
    #   text: "Get Scores"
    #   url: "https://docs.google.com/spreadsheets/d/1Y1Oxw_2LBWd502JtWFFyef2y5TvOyQMkq156cDrKJbA"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} datainconsistencies'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

#features:
#  comment:
#    provider: 'giscus'
#    giscus:
#      repo: 'data-inconsistencies/landingpage-comments'
#      repo_id: 'R_kgDOM_WnDw'
#      category: 'Q&A'
#      category_id: 'DIC_kwDOM_WnD84CjTmS'
